import Head from 'next/head';

import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Calculator</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/cat.ico" />
			</Head>
			<div className={styles.container}>hello world</div>
		</div>
	);
}
